name: "phpunit integration standalone"

on:
  pull_request:
  push:

jobs:
  phpunit_integration_standalone:
    name: "phpunit integration standalone"
    runs-on: ${{ matrix.operating-system }}

    concurrency:
      group: phpunit-standalone-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "7.4"
        operating-system:
          - "ubuntu-latest"
        include:
          - php-version: "7.4"
            dependencies: "locked"
            operating-system: "ubuntu-latest"

    services:
      solr:
        image: solr:latest
        ports:
          - "8983:8983"
        env:
          SOLR_OPTS: "
                        -Dsolr.ssl.checkPeerName=false
                        -Dsolr.allow.unsafe.resourceloading=true
                    "
        volumes:
          - data:/var/solr

        options: --name solr-standalone-server

    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"

      - name: "setup solr"
        run: |
          docker exec solr-standalone-server bash /opt/solr/bin/solr create -c demo -p 8983 \
          && docker exec solr-standalone-server bash /opt/solr/bin/post -c demo -commit no example/exampledocs/{gb18030-example,hd,ipod_other,ipod_video,manufacturers,mem,money,monitor,monitor2,mp500,sd500,solr,utf8-example,vidcard}.xml \
          && docker exec solr-standalone-server bash /opt/solr/bin/post -c demo -commit no example/exampledocs/books.json \
          && docker exec solr-standalone-server bash /opt/solr/bin/post -c demo -commit yes example/exampledocs/books.csv \

      - name: "install php"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2

      - name: "cache dependencies"
        uses: "actions/cache@v3"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"
          restore-keys: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"

      - name: "install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress --ignore-platform-req=php"

      - name: "install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress --ignore-platform-req=php"

      - name: "install locked dependencies"
        if: ${{ matrix.dependencies == 'locked' }}
        run: "composer install --no-interaction --no-progress --ignore-platform-req=php"

      - name: "phpunit integration tests"
        run: "vendor/bin/phpunit --coverage-clover coverage.xml --testsuite=integration-standalone"
